#title: AVERtek # your name photo (or website title) here
logo1: "images/Company Here.jpg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>CRUSH IT</h1></b></a> 
  <h1 style="text-align: center;" markdown="1"></b><a href="https://www.crushitwithchallenges.com/join-challenges23" onclick="getOutboundLink('https://www.crushitwithchallenges.com/join-challenges23'); return false;"<b> WITH CHALLENGES</h1></b></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHO:</b><a href="http://bit.ly/DodgerGearAB" onclick="getOutboundLink('http://bit.ly/DodgerGearAB'); return false;"<b> WINS</b><h/2></a>
  <br><br> 
  <h2 style="text-align: center;" markdown="1"><b>WHAT:</b><a href="https://www.mlb.com/dodgers/schedule/2021-03" onclick="getOutboundLink('https://www.mlb.com/dodgers/schedule/2021-03'); return false;"<b> IT WORKS</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHERE:</b><a href="https://www.mlb.com/dodgers/tickets" onclick="getOutboundLink('https://www.mlb.com/dodgers/tickets'); return false;"<b> DOES IT APPLY</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHY:</b><a href="https://avertek.github.io/Alexan-Bahay-1Bd/" onclick="getOutboundLink('https://avertek.github.io/Alexan-Bahay-1Bd/'); return false;"<b> IS THE RIGHT TIME</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>HOW:</b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> EASY IS IT</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-00000000-0 
