#title: AVERtek # your name photo (or website title) here
logo1: "images/Company Here.jpg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>Strategies for Entrepreneurs</h1></b></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>HOW TO TURN HOBBIES</b><a href="https://100xpodcast.libsyn.com/345-the-two-things-every-successful-entrepreneur-has-in-common" onclick="getOutboundLink('https://100xpodcast.libsyn.com/345-the-two-things-every-successful-entrepreneur-has-in-common'); return false;"<b> INTO REVENUE</b><h/2></a>
  <br><br> 
  <h2 style="text-align: center;" markdown="1"><b>SUCCESSFUL LAUNCH</b><a href="https://www.100xacademy.com/academy" onclick="getOutboundLink('https://www.100xacademy.com/academy'); return false;"<b> TOOLS</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>NEXT LEVEL</b><a href="https://100xpodcast.libsyn.com/" onclick="getOutboundLink('https://100xpodcast.libsyn.com/'); return false;"<b> MARKETING</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>SCALING BUSINESS</b><a href="https://onefunnelaway.com/challenge-c?affiliate_id=451382&cf_affiliate_id=451382" onclick="getOutboundLink('https://onefunnelaway.com/challenge-c?affiliate_id=451382&cf_affiliate_id=451382'); return false;"<b> INTELLEGENTLY</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>FIND OUT IF THIS IS</b><a href="https://100x.zendesk.com/hc/en-us" onclick="getOutboundLink('https://100x.zendesk.com/hc/en-us'); return false;"<b> RIGHT FOR YOU?</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-00000000-0 
