#title: AVERtek # your name photo (or website title) here
logo1: "images/Company Here.jpg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>CRUSH IT</h1></b></a> 
  <h1 style="text-align: center;" markdown="1"></b><a href="https://100x.zendesk.com/hc/en-us/articles/360058136593-What-Is-A-Challenge-" onclick="getOutboundLink('https://100x.zendesk.com/hc/en-us/articles/360058136593-What-Is-A-Challenge-'); return false;"<b> WITH CHALLENGES</h1></b></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHO</b><a href="https://100xpodcast.libsyn.com/345-the-two-things-every-successful-entrepreneur-has-in-common" onclick="getOutboundLink('https://100xpodcast.libsyn.com/345-the-two-things-every-successful-entrepreneur-has-in-common'); return false;"<b> WINS?</b><h/2></a>
  <br><br> 
  <h2 style="text-align: center;" markdown="1"><b>WHAT</b><a href="https://www.100xacademy.com/academy" onclick="getOutboundLink('https://www.100xacademy.com/academy'); return false;"<b> IS IT?</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHERE</b><a href="https://100xpodcast.libsyn.com/" onclick="getOutboundLink('https://100xpodcast.libsyn.com/'); return false;"<b> DOES IT APPLY?</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHEN'S</b><a href="https://onefunnelaway.com/challenge-c?affiliate_id=451382&cf_affiliate_id=451382" onclick="getOutboundLink('https://onefunnelaway.com/challenge-c?affiliate_id=451382&cf_affiliate_id=451382'); return false;"<b> THE RIGHT TIME?</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>WHY</b><a href="https://100x.zendesk.com/hc/en-us" onclick="getOutboundLink('https://100x.zendesk.com/hc/en-us'); return false;"<b> NOW?</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-00000000-0 
